branches:
  only:
  - gh-pages
  - /.*/
language: python
python:
- 3.6
install:
- pip install -r requirements.txt
script:
- make html
notifications:
  email:
    on_success: always
    on_failure: always
env:
  global:
  - secure: pt9kYDhwgh8vqzDwP6rRdoFZi9G0HbRv4PyPEio2KwTuK/Rk6Lzgq9oMFjTERpR8wLkEhyadYlv0A1+LfTljBy+yPDSODX0sHgZ9C4JnPO0PCiyV+5CtktjP0yWgfxJ3vs/nOveZZ38Id0bji4yFbxPtbmHJanJUqlkplrC0E+qBLx3pgTnmby8kVgIpwbJmFtkzzuzMWFLw4XfsOmbRlogHW85t1pZFPr/JEtGd56Cv1ZpyL2u7Iyj1tLeS4+ec+Gk0d0+uujyfklIs2dx7Ccf362irkjBIQWPa/1iB/UCnr88xbEGhQoWR3VYj4OLcwPRn9np2OLBp/FkRMQ0DyG9k+Mkys8/i94VgGHUmNHUTBPtKFcumNbXDyJ9MYzsHKKYDNUpbBPMJGjz7MK7OLqSAyYjs75Yeobssfr/RlNBFzZ+5yeRJKpJ6rSqA+RX+1BdqI9yvgB+hZAm/rfAbdWkLqUkPt9psKfb6di8enikfLCizKimwIR+QVHPthNxxJUWM0NNLgEJ3C7U7cB/LMQVXVcSlduQkRz/Q6iRyEu/HWwOVkB2ZmckPPCgmwek2EcNTLooEZWqQy3ebu/DS7/l3pop8haBNYrpjHaqzsaIv2f4irtLzPy9zU+Dqu8jrr8T9mFCQs5fXMNncNT6yQVyTLhXMyyniGTfnk1+7akw=
before_install:
- git submodule update --init --recursive
after_success: bash deploy.sh
